use anyhow::Result;

pub use buffer::Buffer;
pub use indent::Indented;
pub use stdout::StdOut;

mod buffer;
mod indent;
mod stdout;

/// An [Output] translates data generated by an apyxl [Generator] to some output format.
pub trait Output {
    fn write_str(&mut self, data: &str) -> Result<()>;
    fn write(&mut self, data: char) -> Result<()>;
    fn newline(&mut self) -> Result<()>;
}
