mod stdout;

pub use stdout::StdOut;

use anyhow::Result;

/// An [Output] translates data generated by an apyxl [Generator] to some output format.
pub trait Output {
    fn write(&self, data: &str) -> Result<()>;
}
